vapor/async-kit

Sources/NIOKit/ConnectionPool.swift, Tests/LinuxMain.swift, Tests/NIOKitTests/ConnectionPoolTests.swift, Tests/NIOKitTests/FutureOperatorsTests.swift, Tests/NIOKitTests/NIOKitTests.swift, circle.yml
Changes `ConnectionPool` storage from `Array` to `CircularBuffer`.
=> use circular buffer for connection pool

Package.swift, Sources/NIOKit/FutureExtensions.swift, Tests/LinuxMain.swift, Tests/NIOKitTests/FutureExtensionsTests.swift
Mimics the simple `guard` statement in Swift. Useful for verifying a condition of the future before moving forward.
Example usage:
```swift
.guard({ order.userID == user.id }, else: AccessError.unauthorized)
```
=> Add guard future extension

Sources/NIOKit/Transform.swift
This avoids creating the argument if it won't be needed at all, e.g. because a previous future fails.
=> Wrap the argument to `Future.transform` in an autoclosure

.github/PULL_REQUEST_TEMPLATE.md
Adds a checkbox to the PR template so the linuxmain is regenerated every time new tests are added, to prevent us from missing tests on Linux on accident.
=> Add checkbox for `swift test --generate-linuxmain`

Sources/NIOKit/ConnectionPool.swift, Sources/NIOKit/EventLoopFuture/Collection+Flatten.swift, Tests/NIOKitTests/ConnectionPoolTests.swift, Tests/NIOKitTests/XCTestManifests.swift, circle.yml
This PR adds a new `close()` method to `ConnectionPool`. This method is used to close all of the pool's active connections. In Vapor 4, connections  _must_ be closed before they deinitialize to ensure no memory is leaked. This change allows for connections created from a pool to follow this rule.
To help catch bugs early, connection pool will behave similarly to connections and cause an assertion failure if it deinitializes without being closed first. 
Some other notes:
I noticed that `flatten()` to `EventLoopFuture<Void>` was missing, so I added it.
There was a bug that caused connect failures to increment the active connection count without returning a connection. This has been fixed by decrementing the active connection count if creating a connection ever fails.
=> add ConnectionPool.close() + fix connect error bug

Sources/AsyncKit/EventLoopFuture/Future+Collection.swift, Tests/AsyncKitTests/Future+CollectionTests.swift
Adds:
- `flatMapEachThrowing()` - identical to `mapEach()`, except that the body may throw an error. Any error thrown, regardless of which element of the sequence it was, fails the entire future.
- `flatMapEachCompactThrowing()` - identical to `mapEachCompact()` except with throwing bodies.
- Unit tests for both.
=> Add helpers for throwing closures when mapping sequences

Sources/AsyncKit/EventLoopFuture/Future+Throwing.swift, Tests/AsyncKitTests/FutureExtensionsTests.swift
Very simple, includes a test anyway.
=> Add sugar for starting a future chain with a throwing closure.

Sources/AsyncKit/EventLoopFuture/EventLoopFutureQueue+Sequence.swift, Tests/AsyncKitTests/EventLoopFutureQueueTests.swift
These methods correspond to the `flatten(on:)` methods on `EventLoopGroup` and serve much the same purpose, while leveraging the strict ordering guarantees of the queue.
=> Add methods to EventLoopFutureQueue for queueing sequences

Sources/AsyncKit/EventLoopFuture/EventLoopFutureQueue.swift, Tests/AsyncKitTests/ConnectionPoolTests.swift, Tests/AsyncKitTests/EventLoopFutureQueueTests.swift
Wraps `append(onPrevious:generator:)` in an `EventLoop.flatSubmit()` invocation to serve as a stopgap fix against thread-unsafe behavior in the method body. Change was authored by @calebkleveter. Thanks to @Lukasa for the heads-up on the problem.
=> Quick fix for thread safety issue in EventLoopFutureQueue

Sources/AsyncKit/EventLoopFuture/EventLoopFutureQueue+Sequence.swift, Tests/AsyncKitTests/EventLoopFutureQueueTests.swift, Tests/AsyncKitTests/XCTestManifests.swift
Currently, if one of the futures appended by `EventLoopFutureQueue.append(each:generator:)` fails, we fire an incorrect assertion instead of failing the chain correctly. This PR fixes the issue and adds unit tests.
=> Don't assert when a future in a queued sequence fails

Sources/AsyncKit/EventLoopFuture/EventLoopFutureQueue+Sequence.swift, Tests/AsyncKitTests/EventLoopFutureQueueTests.swift
Previous PR (#54) did not fully fix the problem with appending sequences to `EventLoopFutureQueue`. This PR covers the missing bits.
=> Finish fixing sequence append for ELFQueue

.github/PULL_REQUEST_TEMPLATE.md
Since everything now uses `--enable-test-discovery` regenerating the LinuxMain and test manifests is no longer needed for new PRs
=> Remove checklist item for regenerating LinuxMain.swift

Sources/AsyncKit/EventLoopFuture/EventLoopFutureQueue.swift, Tests/AsyncKitTests/EventLoopFutureQueueTests.swift
The `EventLoopFutureQueue.ContinueError.previousError` case will now be flattened when printed.
=> Conform EventLoopFutureQueue.ContinueError to CustomStringConvertible

.github/workflows/test.yml, Sources/AsyncKit/ConnectionPool/EventLoopGroupConnectionPool.swift, Sources/AsyncKit/EventLoop/EventLoop+Future.swift, Sources/AsyncKit/EventLoopFuture/FutureExtensions.swift, Tests/AsyncKitTests/AsyncKitTests.swift, Tests/AsyncKitTests/ConnectionPoolTests.swift, Tests/AsyncKitTests/EventLoopFutureQueueTests.swift, Tests/AsyncKitTests/EventLoopGroup+Future.swift, Tests/AsyncKitTests/FlattenTests.swift, Tests/AsyncKitTests/Future+CollectionTests.swift, Tests/AsyncKitTests/Future+OptionalTests.swift, Tests/AsyncKitTests/FutureExtensionsTests.swift, Tests/AsyncKitTests/FutureOperatorsTests.swift, Tests/AsyncKitTests/TransformTests.swift
- Soft-deprecate (documentation only, no warnings from the compiler) `EventLoopGroupConnectionPool.shutdown()` for being unnecessarily synchronous (among other things).
- Add `EventLoopGroupConnectionPool.shutdownGracefully(_:)`, modeled loosely after `EventLoopGroup.shutdownGracefully(queue:_:)`. Shutdown takes place asynchronously, and a callback is invoked on a "safe" Dispatch queue to notify of completion and any errors.
- Add `EventLoopGroupConnectionPool.syncShutdownGracefully()`, modeled rather closely after `EventLoopGroup.syncShutdownGracefully()`. Shutdown is synchronous from the point of view of calling code. As with any such method, it must not be invoked on any of the `EventLoop`s in the pool's `EventLoopGroup`, otherwise deadlock will result. Any error that occurs is thrown. …
=> New and better-behaved shutdown methods for `EventLoopGroupConnectionPool`

Sources/AsyncKit/EventLoopFuture/EventLoopFutureQueue.swift
Due to a change in Swift, all Errors became CustomStringConvertible by virtue of implicit bridging with NSError. The check for CustomStringConvertible conformance has been removed. This restores the previous behavior and makes the tests pass again.
Unblocks #67
=> Fix bug related to swift change in error string conversion

Sources/AsyncKit/ConnectionPool/ConnectionPoolError.swift, Sources/AsyncKit/ConnectionPool/EventLoopConnectionPool.swift, Sources/AsyncKit/ConnectionPool/EventLoopGroupConnectionPool.swift, Tests/AsyncKitTests/ConnectionPoolTests.swift, Tests/AsyncKitTests/EventLoopFutureQueueTests.swift
Fixes a bug when requesting `n+1` connections from a connection pool with limit `n` where each new connection waited on the previous one.
Previously, this would create a deadlock. Now, a timeout can be added to `EventLoopConnectionPool`, that will return a failed future if the timeout is reached. Timeout defaults to 10 seconds but can be configured.
Fixes #63
=> Timeout connection requests when in a deadlock.

Sources/AsyncKit/ConnectionPool/ConnectionPoolItem.swift
Fixes the following warnings now produced by the Swift 5.4 compiler:
```
warning: using 'class' keyword for protocol inheritance is deprecated; use 'AnyObject' instead
public protocol ConnectionPoolItem: class {
^~~~~
AnyObject
```
=> Fix warnings from Swift 5.4 compiler

Sources/AsyncKit/EventLoopFuture/Future+Conjunctions.swift, Sources/AsyncKit/EventLoopFuture/Optional+StrictMap.swift, Tests/AsyncKitTests/Future+ConjunctionTests.swift
- `strictMap()` is a global function providing the services of `Optional.map()` for multiple optionals at once: `strictMap(a, b, { foo($0, $1) })` is equivalent to (but slightly more efficient than) `a.flatMap { a in b.map { b in foo(a, b) } }`.
- `EventLoopFuture.whenTheySucceed()` provides the "wait for all to succeed or any to fail" semantics of `.whenAllSucceed()` for a heterogenous set of futures. Or in other words, it's a more-than-two-futures version of `.and()`: `EventLoopFuture.whenTheySucceed(f1, f2, f3)` is equivalent to (but _much_ more efficient than) `f1.and(f2).and(f3).map { ($0.0, $0.1, $1) }`.
=> Add `strictMap()` and `EventLoopFuture.whenTheySucceed()`

Sources/AsyncKit/EventLoopFuture/Future+Collection.swift, Tests/AsyncKitTests/Future+CollectionTests.swift
This is effectively a convenience for using `EventLoopFuture.andAllSucceed(_:on:)`.
=> Add overload of flatMapEach(on:_:) for Void futures

Sources/AsyncKit/EventLoopFuture/Future+Try.swift, Tests/AsyncKitTests/Future+TryTests.swift
One of the most common hurdles of working with EventLoopFutures, and a very oft-repeated question on the Discord server is interacting with error-throwing code. The `tryFlatMap` extension alleviates that by handling any errors thrown by the closure, causing the ELF to fail.
This is the most common error handling pattern anyway.
=> Add `EventLoopFuture.tryFlatMap()` by popular demand

Sources/AsyncKit/EventLoopFuture/Future+Try.swift
removed due to depreciation warnings issued with latest Vapor.
Removes depreciated parameters `file:line:` from method signature and calling method.
=> Removed file:line: from signature and code in Future+Try.swift

.github/workflows/main-codecov.yml, .github/workflows/test.yml, Package.swift
This removes support for Swift 5.2 and Swift 5.3, making Swift 5.4 the earliest supported version [as announced](https://blog.vapor.codes/posts/vapor-swift-versions-update/)
=> Update Supported Swift Versions

Package.swift, Sources/AsyncKit/EventLoop/EventLoop+Concurrency.swift, Sources/AsyncKit/EventLoop/EventLoopGroup+Concurrency.swift, Tests/AsyncKitTests/EventLoop+ConcurrencyTests.swift
Enables concurrency features on macOS 10.15 et al. Drops support for Swift 5.5.0 and 5.5.1 to match SwiftNIO
=> Back deploy concurrency to older Apple Platforms

Package.swift, Sources/AsyncKit/ConnectionPool/EventLoopConnectionPool.swift, Tests/AsyncKitTests/ConnectionPoolTests.swift
This is a temporary stopgap measure to clean up some of the more extant issues with the existing implementation, pending the integration of a much more robust and advanced connection pool solution.
While technically there is no change in the public API surface, this is nonetheless being marked as semver-minor due to the significant changes in behavior. This PR has already revealed a query ordering bug in the Fluent benchmarks just by behaving more correctly.
This _should_ hopefully fix the issue described in #101, but I haven't been able to locally reproduce the race condition despite being fairly sure as to its cause, so I can't verify.
- Now uses `Deque` instead of the obsolete `CircularBuffer` for tracking available connections
- Now uses an `OrderedDictionary` and numeric waiter IDs …
=> Heavily revise the implementation of EventLoopConnectionPool

Sources/AsyncKit/ConnectionPool/EventLoopConnectionPool.swift
There's a parenthesis missing in the connection request error message.
This fixes https://github.com/vapor/async-kit/issues/107.
=> Fix typo in connection request error message
